### ISSUE TITLE
Lack of error messages and token.json not remade

### ISSUE THREAD

**Issue by stevebrewcon** [AIKEJI-AU/Xero.OAuth2.Docs#1]
Using v1.4.0

Testing on demo account. Had to remake the app. Also remade local program in Visual Studio.

No error message when I forgot to install aikeji.lic

token.json had to be taken out. On starting the program a confirmation screen did not open and the token.json was not replaced. I had to run an older program to get a new token.json

**Comment by shellicar-aikeji** [comment]
Hi Steve,

Thanks for reporting the issue.
Can you provide some additional details?
**The immediate code calling `GetToken`**
**The debug output log.**
**The version of the library you're using for each application.**

*No error message when I forgot to install aikeji.lic*
Do you have the `GetToken` method wrapped in a try catch?

*On starting the program a confirmation screen did not open and the token.json was not replaced*
What confirmation screen are you talking about?

**Comment by stevebrewcon** [comment]
Hello Stephen,

The code is as you supplied. I have not altered it.

Library version which worked was v1.3. I am using a demo Xero account which expired and had to be remade, therefore the app had to be remade. I have also had issues when upgrading RestSharp so I made a new Visual Studio project, pasted in the code and imported the Nuget modules. Everything fresh and clean.

I did not save any logs.

Now on library v1.4.

I got the index out of range error which I remembered was related to an old token.json file. I took out the old file and the program froze.

When connecting to the Xero app for the first time a browser opens a login requiring username and password. Is this your embedded browser? This did not happen. Eventually I opened an old program in v1.3 which worked. I then copied the token.json file to the new project.

Regards

Steve

Sent from Mail for Windows 10

**Comment by shellicar-aikeji** [comment]
Hi Steve,

We have identified an issue that occurs when the calling code is not using Async with version 1.4.0 of the library.
We have fixed the issue internally and this will be available in our next release.

In the mean time, you can avoid the "freeze" by staying on version 1.3.0 of the library.
Or by ensuring your methods are all Async, and use Await, rather than calling .Result

eg:
Instead of
```
Dim accessToken = _tokenHelper.GetToken().Result.AccessToken
```
Use
```
Dim accessToken = (Await _tokenHelper.GetToken()).AccessToken
```

**Comment by stevebrewcon** [comment]
Hello Stephen,

I have reverted to v1.3.

Having got everything working from visual studio, I find the published version delivers the following error.

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\Users\Steve\AppData\Local\Apps\2.0\OJWNW517.Y3J\6D408XA1.G9Q\brew..tion_c6eb49a8cca5349c_0001.0000_ea392ca9a0c06c4f\aikeji.lic'.
File name: 'C:\Users\Steve\AppData\Local\Apps\2.0\OJWNW517.Y3J\6D408XA1.G9Q\brew..tion_c6eb49a8cca5349c_0001.0000_ea392ca9a0c06c4f\aikeji.lic'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at AIKEJI.Xero.OAuth2.License.AIKEJILicenseHelper.AssertLicense()

I have posted this on GitHub

Following this I am a little concerned as to how the token.json file is integrated into a customer’s installation. The compiled assembly does not have a bin and therefore this file will need to be created somewhere else by the customer’s installation. The compiler is including the original token.json file in the published assembly. A customer will need to generate a new token.json file via your embedded browser. How will this integrate with the published assembly?

Regards

Steve




Sent from Mail for Windows 10

**Comment by shellicar-aikeji** [comment]
Hi Steve,

We have released a new version which should fix the issue.

1.4.1 is now on nuget.org and fixes the "freeze".
We have also updated our testing so that this issue will not occur again.

If you have a query about how the library functions, can you please put it as a separate question?
This helps keep each issue focused and related to the issue's topic.
