### ISSUE TITLE
token.json

### ISSUE THREAD

**Issue by stevebrewcon** [AIKEJI-AU/Xero.OAuth2.Docs#3]
Using Visual Studio in Debug and Release, if the token.json needs to be refreshed, the program freezes. Token has to be manually deleted.

The published version works perfectly.

**Comment by alice-aikeji** [comment]
Hi Steve, when the access token expires and needs to be refreshed, the library will first try and use the refresh token to refresh it. If somehow it fails to complete the refresh successfully, e.g. refresh token is also expired, the library will prompt up the log in process again. Could you include detailed instructions for us to replicate what you experienced together with the version of Visual Studio you are using and other relevant information?

Thank you.

**Comment by stevebrewcon** [comment]
Hello Alice,

Do you have the wrong person here? I did not contact you.

Regards

Steve

Sent from Mail for Windows 10
