### ISSUE TITLE
Error Loading DLL

### ISSUE THREAD

**Issue by shashwahpple** [AIKEJI-AU/Xero.OAuth2.Docs#4]
When attempting to run my application on a different machine, I encounter the following exception

> System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found. File name: 'CefSharp.Core.dll' at AIKEJI.Xero.OAuth2.Internal.CefHelper.InitialiseCef(TokenHelperOptions options) at AIKEJI.Xero.OAuth2.Internal.Controls.LoginForm..ctor(TokenHelperOptions options, IAuthFlowHandler handler) at AIKEJI.Xero.OAuth2.Internal.FormsTokenProvider.d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at AIKEJI.Xero.OAuth2.Internal.TokenHelperInternal.d__17.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at AIKEJI.Xero.OAuth2.Internal.TokenHelperInternal.d__15.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at AIKEJI.Xero.OAuth2.TokenHelper.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at TSSFlow.XeroWrapper.RefreshAccessInit() in C:\...\XeroWrapper.cs:line 56 

The application runs perfectly in the environment it was built in, but on a different machine the exception occurs despite all the dlls and associated files being in the directory.
I've tried downgrading the library to v1.5.0 which hasn't worked,
The following exception message is what has appeared when attempting to call the library since downgrading to v1.5.0

> System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core, Version=79.1.360.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The specified module could not be found. File name: 'CefSharp.Core, Version=79.1.360.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' ---> System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found. File name: 'CefSharp.Core.dll' at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence) at System.Reflection.Assembly.LoadFile(String path) at AIKEJI.Xero.OAuth2.Internal.ModuleInit.OnAssemblyResolve(Object sender, ResolveEventArgs args) at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName) at AIKEJI.Xero.OAuth2.Internal.CefHelper.ClearLogin(TokenHelperOptions options) at AIKEJI.Xero.OAuth2.Internal.FormsTokenProvider.ClearSession(TokenHelperOptions options) at AIKEJI.Xero.OAuth2.Internal.TokenHelperInternal.ClearLoginSessionInternal() at AIKEJI.Xero.OAuth2.TokenHelper.ClearLoginSession() at TSSFlow.XeroWrapper.ClearLogin() in C:\...\XeroWrapper.cs:line 33 

I'm unsure if this matters but the application is running .NET version 4.6.1 with the correct redistributable installed

**Comment by GatorMike67** [comment]
I have the same issue - need help immediately please. Was there any solution to this?

**Comment by alice-aikeji** [comment]
> I have the same issue - need help immediately please. Was there any solution to this?

Hi Mike,

We looked into this issue when it was raised in Jan. When things like this happen it is environment specific so it's hard to replicate and diagnose. We didn't manage to replicate the issue in our environment. The library continues to function well in our local and test environment.
The customer who raised this issue implemented the following solution which resolved the problem:
**Adding the path for the CefSharp dependencies into my App.config file.**

Maybe give that a try and see if it fixes the issue?

We are happy to send through the dependency package to help with the troubleshooting.

Kind regards,
Alice
